version: '3.8'

services:
  # 1. Le Cerveau
  backend:
    build: ./backend
    # On ne met PLUS de "ports:" ici, car on veut que seul Nginx y accède.
    depends_on:
      - database # On attend que la base soit prête avant de lancer le back
    environment:
      - MONGO_URL=mongodb://database:27017/mon_app

  # 2. Le Visage
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html

  # 3. Le Gardien (Le seul point d'entrée)
  proxy:
    image: nginx:alpine
    volumes:
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80" # Ton site sera accessible sur http://localhost tout court !
   

      # --- LA MÉMOIRE (NOUVEAU) ---
  database:
    image: mongo:latest
    ports:
      - "27017:27017" # <--- Ajoute cette ligne
    volumes:
      - mongodb_data:/data/db # Pour ne pas perdre tes données si tu coupes Docker


  admin-db:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=database
    depends_on:
      - database
      
volumes:
  mongodb_data: # Espace de stockage permanent