version: '3.8'

services:
  # 1. Le Cerveau
  backend:
    build: ./backend
    # On ne met PLUS de "ports:" ici, car on veut que seul Nginx y accède.

  # 2. Le Visage
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html

  # 3. Le Gardien (Le seul point d'entrée)
  proxy:
    image: nginx:alpine
    volumes:
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80" # Ton site sera accessible sur http://localhost tout court !
    depends_on:
      - backend
      - frontend