version: '3.8'

services:
  # Notre serveur de donn√©es
  mon-api:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - reseau-app

  # Notre interface utilisateur
  mon-interface:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - reseau-app

networks:
  reseau-app: